[tool.poetry]
name = "nonebot-plugin-bawiki"
version = "0.5.0b1"
description = "A nonebot2 plugin for Blue Archive."
authors = ["student_2333 <lgc2333@126.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lgc2333/nonebot-plugin-bawiki/"
keywords = ["blue archive", "nonebot", "nonebot2", "bot", "qq"]
classifiers = [
    "Natural Language :: Chinese (Simplified)",
    "Topic :: Communications",
    "Topic :: Communications :: Chat",
    "Topic :: Communications :: Chat :: ICQ",
    "Topic :: Games/Entertainment",
    "Topic :: Games/Entertainment :: Board Games",
    "Topic :: Games/Entertainment :: Turn Based Strategy",
    "Topic :: Games/Entertainment :: Side-Scrolling/Arcade Games",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Wiki"
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
aiohttp = "^3.8.1"
nonebot2 = "^2.0.0-beta.5"
nonebot-adapter-onebot = "^2.1.1"
nonebot-plugin-htmlrender = "^0.1.1"
Pillow = "^9.2.0"
nonebot-plugin-imageutils = "^0.1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
